name: Auto-Update N8N on Railway

on:
  schedule:
    - cron: '0 3 * * MON' # Запускать каждый понедельник в 03:00 UTC
  workflow_dispatch:

jobs:
  redeploy-n8n:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Railway Project and Service IDs
        id: railway_ids
        run: |
          echo "RAILWAY_PROJECT_ID=${{ vars.RAILWAY_PROJECT_ID }}" >> $GITHUB_ENV
          echo "RAILWAY_SERVICE_ID=${{ vars.RAILWAY_SERVICE_ID }}" >> $GITHUB_ENV
        env:
          RAILWAY_PROJECT_ID: c69d3df3-6bc6-454e-9468-67971def343a # Ваш ID проекта
          RAILWAY_SERVICE_ID: c4ffd1ef-026f-4fe4-9365-7aa7d046cec8 # Ваш ID сервиса N8N

      # НОВЫЙ ШАГ ВМЕСТО ПРЕДЫДУЩЕГО С CURL
      - name: Deploy to Railway (with no-cache)
        uses: railwayapp/gh-action@v3
        with:
          service: ${{ env.RAILWAY_SERVICE_ID }}
          project: ${{ env.RAILWAY_PROJECT_ID }}
          token: ${{ secrets.RAILWAY_TOKEN }}
          no_cache: true # Этот параметр заставит Railway пересобрать образ без кэша.
